services:
  # Servicio para los emuladores de Firebase
  firebase-emulators:
    build:
      context: .
      dockerfile: deployments/Dockerfile.firebase
    container_name: firebase-tools
    ports:
      - "9199:9199"  # Storage Emulator
      - "9099:9099"  # Auth Emulator
      - "8080:8080"  # Firestore Emulator
      - "4000:4000"  # Emulator UI
    volumes:
      - ./firebase:/app/firebase:ro
      - ./scripts:/app/scripts:ro
      - ./fixtures:/app/fixtures:ro
      - ./package.json:/app/package.json:ro
      - ./tsconfig.json:/app/tsconfig.json:ro
      - ./.env:/app/.env:ro
    networks:
      - kodem-network

  # Servicio para la aplicación web con Bun
  web:
    build:
      context: .
      dockerfile: deployments/Dockerfile.web
    user: "1000:1000"
    ports:
      - "3000:3000"  # Puerto para Vite
    environment:
      - NODE_ENV=development
      # Variables para los emuladores de Firebase
      - VITE_USE_FIREBASE_EMULATORS=true
      - VITE_FIREBASE_AUTH_EMULATOR_URL=http://firebase-emulators:9099
      - VITE_FIREBASE_FIRESTORE_EMULATOR_HOST=firebase-emulators
      - VITE_FIREBASE_FIRESTORE_EMULATOR_PORT=8080
      - VITE_FIREBASE_STORAGE_EMULATOR_HOST=firebase-emulators
      - VITE_FIREBASE_STORAGE_EMULATOR_PORT=9199
      - VITE_FIREBASE_PROJECT_ID=kodemcards
    volumes:
      - .:/app:z
    depends_on:
      - firebase-emulators
    networks:
      - kodem-network


networks:
  kodem-network:
    driver: bridge 